Fix a ValueError due to parsing nyxrc.sample.
Traceback:
  [...]
  raise ValueError("The '%s' entry of config entry '%s' wasn't in the enumeration (expected %s)" % (val, key, ', '.join(enum_keys)))
    ValueError: The 'LISTING' entry of config entry 'features.connection.order' wasn't in the enumeration (expected CATEGORY, UPTIME, IP_ADDRESS, PORT, FINGERPRINT, NICKNAME, COUNTRY)