Fix AttributeError from connections panel due to unimplemented Stem feature.
Traceback (most recent call last):
  File "/usr/local/bin/nyx", line 8, in <module>
    nyx.main()
  File "/usr/local/lib/python2.7/dist-packages/nyx/__init__.py", line 31, in main
    nyx.starter.main()
  File "/usr/local/lib/python2.7/dist-packages/stem/util/conf.py", line 288, in wrapped
    return func(*args, config = config, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/nyx/starter.py", line 91, in main
    curses.wrapper(nyx.controller.start_nyx)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/nyx/controller.py", line 624, in start_nyx
    is_keystroke_consumed = panel_impl.handle_key(key)
  File "/usr/local/lib/python2.7/dist-packages/nyx/connection_panel.py", line 318, in handle_key
    user_traffic_allowed = tor_controller().is_user_traffic_allowed()
AttributeError: 'Controller' object has no attribute 'is_user_traffic_allowed'